### ISSUE TITLE
Support "unit" name via jounrnalctl and controlling name in journal logs?

### ISSUE THREAD

**Issue by iangregsondev** [ssgreg/journald#5]
Hi,

Is it possible to use the "journal -u test" to get only messages from "test" unit.

I tried this ( i tried adding the WithName but this doesn't seem to do anything in my case)

```
	// Create Logger with ChannelWriter.
	logger := logf.NewLogger(logf.LevelInfo, writer).WithName("test")

	logger.Info("IAN got cpu info", logf.Int("count", runtime.NumCPU()))
```

but it didn't work.

If I look in the logs, it is there but I can't specify the unit.

Here is the example of the log

```
Oct 19 13:08:11 kube01 testme.go.gorun[253735]: IAN got cpu info
```

Another thing that I am not sure if it's possible to control, but you notice the "testme.go.gorun", is it possible to control that ?

I am using gorun with a go file.. my go file is called testme.go and obviously running the "gorun".

I was wondering if we can just replace this with something custom i.e  "test"

Any help really appreciated

Thanks in advance

**Comment by ssgreg** [comment]
Hi,

testme.go.gorun is the name of your unit (a name of your executable). You can build your executable with any name.

You can also filter your logs by any field you use, for example by a constant in WithName:

```
journalctl LOGGER=test
```

To see all fields use:
```
journalctl --output verbose
```
or
```
journalctl --output json
```

**Comment by iangregsondev** [comment]
Thanks. Yep, I have seen that now. Thanks fro your help.
